bi/urls.py
from django.conf.urls import url

from . import views

app_name = 'bi'
urlpatterns = [
    url(r'^$', views.show, name='show'),
    url(r'^submit$', views.import_file, name='import_file'),
    url(r'^graph/$', views.graph, name='graph'),
    url(r'^graph/getsub$', views.get_subgraph, name='get_subgraph'),
    url(r'^graph/gselect$', views.graph_select, name='graph_select'),
    url(r'^graph/sgselect$', views.subgraph_select, name='subgraph_select'),
    url(r'^pivot/deleteg$', views.delete_subgraph, name='delete_subgraph'),
    url(r'^pivot/$', views.pivot_page, name='pivot_page'),
    url(r'^pivot/(?P<filename>[-\ \w]+)/$', views.pivot_table, name='pivot_table'),
    url(r'^pivot/cselect$', views.col_select, name='col_select'),
    url(r'^pivot/rselect$', views.row_select, name='row_select'),
    url(r'^pivot/mselect$', views.measure_select, name='measure_select'),
    url(r'^pivot/deletec$', views.delete_col, name='delete_col'),
    url(r'^pivot/deleter$', views.delete_row, name='delete_row'),
] 

myApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bi/', include('bi.urls')),
    url(r'^admin/', admin.site.urls),
]

bi/models.py
from django.db import models


class Bi(models.Model):
    file_name = models.CharField(max_length = 200)
class FileSelect(models.Model):
    file_name = models.CharField(max_length = 200)

class TimeTable(models.Model):
    time = models.CharField(max_length = 20)
    
class DimenTable(models.Model):
    dimension = models.CharField(max_length = 20)
    
class MeasureTable(models.Model):
    measure = models.CharField(max_length = 20)

class Colselect(models.Model):
    column = models.CharField(max_length = 20)

class Rowselect(models.Model):
    row = models.CharField(max_length = 20)

class Measureselect(models.Model):
    measure = models.CharField(max_length = 20)

class Graphselect(models.Model):
    graph = models.CharField(max_length = 20)

class Subgraph(models.Model):
    sub_graph = models.CharField(max_length = 20)

class Selectsub(models.Model):
    sub_select = models.CharField(max_length = 20)

class Graphmeasure(models.Model):
    measure_graph = models.CharField(max_length = 20)

bi/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from datetime import datetime
from .models import Bi, TimeTable, DimenTable, MeasureTable, Colselect, Rowselect, Measureselect, FileSelect, Graphselect, Subgraph, Graphmeasure, Selectsub
from .model_2 import Model
from .create import Create
import csv, os, cgi
from os.path import basename
import json
import itertools 
import pandas as pd

m = Model()
def show(request):
    #Bi.objects.all().delete()
    FileSelect.objects.all().delete()
    Colselect.objects.all().delete()
    Rowselect.objects.all().delete()
    Measureselect.objects.all().delete()
    Graphselect.objects.all().delete()
    Selectsub.objects.all().delete()
    Graphmeasure.objects.all().delete()
    Subgraph.objects.all().delete()
    with open('bi/static/css/data.json', 'w') as f:
        f.write("")
    with open('bi/static/css/table.html', 'w') as f:
        f.write("")
    return render(request, 'bi/home.html', {'all_list':Bi.objects.order_by('file_name')})

def graph(request):
    #Bi.objects.all().delete()
    return render(request, 'bi/graph.html', {'all_time':TimeTable.objects.all(),
                   'all_dim':DimenTable.objects.all(),
                   'all_measure':MeasureTable.objects.all(), 
                   'all_select':Graphselect.objects.all(),
                   'sub_select':Selectsub.objects.all(),
                   'measure':Graphmeasure.objects.all(),
                   'all_sub':Subgraph.objects.all()})

def get_subgraph(request):
    Subgraph.objects.all().delete()
    data = request.GET.get('data')
    for i in FileSelect.objects.all().values_list('file_name', flat=True):
        m.select_file(i)
    if data in m.time:
        data = data + ':Year'
    array = [] 
    for i in m.get_data(data):
        record = Subgraph(sub_graph = i)
        record.save()
        array.append(i)
    return HttpResponse(json.dumps(array))

def subgraph_select(request):
    Selectsub.objects.all().delete()
    data = request.GET.getlist('data[]')
    for i in data:
        record = Selectsub(sub_select = i)
        record.save()
    return HttpResponseRedirect(reverse('bi:graph'))
def graph_select(request):
    data = request.GET.getlist('data[]')
    if data[0] != " ":
        Graphselect.objects.all().delete()
        record = Graphselect(graph = data[0])
        record.save()
    if data[1] != " ":
        Graphmeasure.objects.all().delete()
        record = Graphmeasure(measure_graph = data[1])
        record.save()
    showGraph()
    return HttpResponseRedirect(reverse('bi:graph'))

def showGraph():
    data = []
    df = pd.DataFrame({})
    dimen = ""
    for i in FileSelect.objects.all().values_list('file_name', flat=True):
        m.select_file(i)
    for i in Graphselect.objects.all().values_list('graph', flat=True):
        dimen = i
        if i in m.time:
            col = [i+':Year']
        else:
            col = [i]
    for i in Graphmeasure.objects.all().values_list('measure_graph', flat=True):
        row = ['Measurement']
        r = [[i]]
    c = [[]]
    for i in Selectsub.objects.all().values_list('sub_select', flat=True):
        if dimen in m.time:
            i = int(i)
        c[0].append(i)
    df['label'] = c[0]
    val = []
    if len(row)>0:
        m.keepC.append(m.df)
        for a in range(len(col)):
            m.keepC.append(None)
        for a in range(len(row)):
            m.keepR.append(None)
        sendC = list(itertools.product(*c))
        sendR = list(itertools.product(*r))
        for j in range(len(sendC)):
            m.get_col(col, sendC[j], m.keepC[0])
            for i in range(len(sendR)):
                val.append(m.get_row(row, sendR[i], m.keepR[0], 0))
        df['value'] = val
    out = df.to_json(orient = 'records')
    with open('bi/static/css/data.json', 'w') as f:
        f.write(out)
    

def delete_subgraph(request):
    record = Selectsub.objects.get(pk = int(request.GET.get('data')))
    record.delete()
    return HttpResponseRedirect(reverse('bi:graph'))

def import_file(request):
    if request.method == 'POST':
        try:
            if(str(request.FILES['file']).endswith('.xlsx')):
                filename = str(request.FILES['file'])
                filename = os.path.splitext(filename)[0]
                handle_uploaded_file(request.FILES['file'], filename)
                starschema(filename)
                record = Bi(file_name = filename)
                record.save()
            else:
                raise
        except:
            return render(request, 'bi/import.html',{'error_message':'Please Select xlsx file!!!'})
    return HttpResponseRedirect(reverse('bi:show'))

def pivot_page(request):
    return render(request, 'bi/pivot.html',
                  {'all_time':TimeTable.objects.all(),
                   'all_dim':DimenTable.objects.all(),
                   'all_measure':MeasureTable.objects.all(), 
                   'all_col':Colselect.objects.all(),
                   'measure':Measureselect.objects.all(),
                   'all_row':Rowselect.objects.all()})

def pivot_table(request, filename):
    '''FileSelect.objects.all().delete()
    Colselect.objects.all().delete()
    Rowselect.objects.all().delete()
    Measureselect.objects.all().delete()'''
    m.select_file(filename)
    record = FileSelect(file_name = filename)
    record.save()
    TimeTable.objects.all().delete()
    DimenTable.objects.all().delete()
    MeasureTable.objects.all().delete()
    for i in m.time:
        record = TimeTable(time = i)
        record.save()
    for i in m.dim:
        record = DimenTable(dimension = i)
        record.save()
    for i in m.measure:
        record = MeasureTable(measure = i)
        record.save()
    return HttpResponseRedirect(reverse('bi:pivot_page'))

def col_select(request):
    data = request.GET.getlist('data[]')
    for i in data:
        record = Colselect(column = i)
        record.save()
    return HttpResponseRedirect(reverse('bi:pivot_page'))
def row_select(request):
    data = request.GET.getlist('data[]')
    for i in data:
        record = Rowselect(row = i)
        record.save()
    return HttpResponseRedirect(reverse('bi:pivot_page'))
def measure_select(request):
    data = request.GET.get('data')
    if data != " ":
        Measureselect.objects.all().delete()
        record = Measureselect(measure = data)
        record.save()
    test()
    return HttpResponseRedirect(reverse('bi:pivot_page'))

def test():
    col = []
    row = []
    rows = []
    c = []
    r = []
    value = []
    measure = ""
    for i in FileSelect.objects.all().values_list('file_name', flat=True):
        filename = i
        m.select_file(filename)
    for i in Colselect.objects.all().values_list('column', flat=True):
        if i in m.time:
            i = i+":Year"
        col.append(i)
    for i in Rowselect.objects.all().values_list('row', flat=True):
        if i in m.time:
            i = i+":Year"
        row.append(i)
        rows.append(i)
    for i in Measureselect.objects.all().values_list('measure', flat=True):
        measure = i
    if measure != "":
        row.append("Measurement")
        value.append(measure)
    for i in range(len(col)):
        c.append([])
        for j in m.get_data(col[i]):
            c[i].append(j)
    for i in range(len(row)):
        r.append([])
        if row[i] == 'Measurement':
            r[i].append(measure)
        else:
            for j in m.get_data(row[i]):
                r[i].append(j)
    #print(row)
    df = pd.DataFrame({})
    get_col = []
    get_row = []
    get_value = []
    columns = []
    if len(value) > 0:
        m.keepC.append(m.df)
        for a in range(len(col)):
            get_col.append([])
            m.keepC.append(None)
        for a in range(len(row)):
            get_row.append([])
            m.keepR.append(None)
        sendC = list(itertools.product(*c))
        sendR = list(itertools.product(*r))
        for j in range(len(sendC)):
            m.get_col(col, sendC[j], m.keepC[0])
            for i in range(len(sendR)):
                val = m.get_row(row, sendR[i], m.keepR[0], 0)
                for k in range(len(col)):
                    get_col[k].append(sendC[j][k])
                for l in range(len(row)):
                    get_row[l].append(sendR[i][l])
                get_value.append(val)
                columns.append("Value")
        for i in range(len(col)):
            df[col[i]] = get_col[i]
        for i in range(len(row)):
            df[row[i]] = get_row[i]
        df['Value'] = get_value
        df['Column'] = columns
        if len(col) > 0:
            colu = col
        else:
            colu = ['Column']
        if len(row) > 1:
            index = rows
        else:
            index = ['Measurement']
        table = pd.pivot_table(df, values = 'Value',
                               index = index, columns = colu)
        with open("bi/static/css/table.html", 'w') as fo:
            fo.write(table.to_html())
               

def delete_col(request):
    record = Colselect.objects.get(pk = int(request.GET.get('data')))
    record.delete()
    return HttpResponseRedirect(reverse('bi:pivot_page'))
def delete_row(request):
    record = Rowselect.objects.get(pk = int(request.GET.get('data')))
    record.delete()
    return HttpResponseRedirect(reverse('bi:pivot_page'))

def handle_uploaded_file(file, filename):
    if not os.path.exists('upload/'):
        os.mkdir('upload/')
 
    with open('upload/' + filename+".xlsx", 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

def starschema(filename):
    c = Create()
    c.import_file('./upload/'+filename+".xlsx")
    c.convert_data()
    c.manage_file()
    c.set_file()

bi/templates/bi/home.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <title>BI</title>
  <link rel="shortcut icon" href="{% static 'pic/icon.png' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
  .import_div{
    margin: 60px 0 0 500px
  }
  .import{
    width: 120px;
    height: 60px;
    text-align: center;
    font-size: 24px;
    border-radius: 6px;
    cursor: url({% static 'pic/cat2.png' %}),auto;
    background-color:green  ;
    color:white;
  }
</style>
</head>

<body style="background-image:url({% static 'pic/bg3.jpg' %});">
  <div class="w3-container" style="background-color: black">
    <h1  style="text-align: center; color: white; font-family:Times;">Business Intelligence</h1>        
  </div>

  <div class="w3-quarter" style="background-color:rgba(255, 255, 255, 0.5); height:600px;padding-top: 10px; width: 300px" >
    <h2 style="text-align: center;">Open File</h2>
    <div class="w3-bar-block">
      {% for list in all_list %}
      <a href="{% url 'bi:pivot_table' list.file_name %}" class="w3-bar-item w3-hover-light-grey w3-ripple" style="width: 100%; text-align: left; text-decoration:none">&#8231; {{ list.file_name }}
      </a>
      {% endfor %}
    </div>
  </div>

  <div class="import_div" style="background-color:rgba(255, 255, 255, 0.5); width: 600px;
                                height:400px; text-align: center;">
    <h1 style="padding-top: 50px">Import File</h1>
    <br/><br/>
    <form action="{% url 'bi:import_file' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="file" accept=".xlsx">&nbsp;
      <br/><br/><br/>
      <button class="import" type="submit"><b>UPLOAD</b></button></a>
      <br/><br/><br/>
    </form>
  </div>

</body>
</html>

bi/templates/bi/pivot.html
<!DOCTYPE html>
<html>
{% load static %}
<title>BI</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="/static/pic/icon.png">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://www.w3schools.com/lib/w3data.js"></script>

</head>
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}">
<link rel="html" href="{% static 'css/table.html' %}">

<style type="text/css">
  body {
    background-image: url({% static 'pic/pg.jpg' %});
    background-repeat: no-repeat;
    background-size:cover;

}
</style>
<body>

<!-- Sidebar -->
<div class="w3-sidebar w3-bar-block w3-animate-left w3-grey" style="display:none;z-index:5" id="mySidebar">
  <button class="w3-bar-item w3-button w3-medium w3-black w3-hover-dark-grey" onclick="w3_close()">Close &times;</button>
  <div class="w3-cell-row">
  	<div class="w3-container w3-cell">
    	<h3 style="text-align: center;">Dimension</h3>
  		<div class="w3-dropdown-hover" style="width: 100%">
    		<button class="w3-button w3-green" style="text-align: center;">Select Dimension</button>
    		<div class="w3-dropdown-content w3-bar-block w3-border" style="max-height: 350px; overflow-y:scroll; ">
                    
    			{% for list in all_time %}
      		     <div class="w3-bar-item w3-button w3-ripple">
                        <a href="#" id ="testlink" class="aaa w3-button" style="text-decoration:none;">{{ list.time }}</a>
                     </div>
    			{% endfor %}
    			{% for list in all_dim %}
                    <div class="w3-bar-item w3-button w3-ripple">
      		<a href="#" id ="testlink" class="aaa w3-button" style="text-decoration:none;">{{ list.dimension }}</a>
                    </div>
    			{% endfor %}
                        
    		</div>
  		</div>
  	</div>

  	<div class="w3-container w3-cell">
    	<h3 style="text-align: center;">Measurement</h3>
  		<div class="w3-dropdown-hover" style="width: 100%">
    		<button class="w3-button w3-green" style="text-align: center;">Select Measurement</button>
    		<div class="w3-dropdown-content w3-bar-block w3-border" style="max-height: 350px; overflow-y: scroll;">
    			{% for list in all_measure %}
                <div class="w3-bar-item w3-button w3-ripple">
      		<a href="#" class="bbb w3-button" style="text-decoration:none;">{{ list.measure }}</a>
                </div>
    			{% endfor %}
    		</div>
  		</div>
  	</div>
	</div>
  
	<div class="w3-cell-row" style="margin-top: 40px;">
  	<div class="w3-container w3-cell w3-white	" style="width: 75%;">
   		<h5 style="text-align: center;" id = "select">Dimension :</h5>
  	</div>

  	<div class="w3-container w3-cell">
    	<button id = "colbut" class="w3-container w3-ripple w3-btn w3-pale-red" style="width: 100%">Column</button>
    	<button id = "rowbut" class="w3-container w3-ripple w3-btn w3-pale-green" style="width: 100%">Row</button>
  	</div>

	</div>

	<div class="w3-cell-row" style="margin-top: 40px;">
  	<div class="w3-container w3-cell " style="width: 50%;">
    	<table id="colTable" class="w3-table w3-striped w3-bordered tableSection">
      <thead>
        <tr class="w3-red">
          <th>Column</th>
          <th></th>
        </tr>
      </thead>
      {% for list in all_col %}
      <tr><td>{{list.column}}</td><td><button class="button" style="background-color:green; color:white;" type="submit"><b>+</b></button><button class="button" onclick="deleteCol(this,{{list.id}})" style="background-color:red; color:white;"type="submit"><b>-</b></button></td></tr>
      {% endfor %}
    	</table>
  	</div>

  	<div class="w3-container w3-cell " style="width: 50%">
    	<table id = "rowTable" class="w3-table w3-striped w3-bordered tableSection">
      <thead>
        <tr class="w3-red"> 
          <th>Row</th>
          <th></th>
        </tr>
      </thead>
      {% for list in all_row %}
      <tr><td>{{list.row}}</td><td><button class="button" style="background-color:green; color:white;" type="submit"><b>+</b></button><button class="button" onclick="deleteRow(this,{{list.id}})" style="background-color:red; color:white;"type="submit"><b>-</b></button></td></tr>
      {% endfor %}
    	</table>
  	</div>
	</div>

    <div class="w3-cell-row" style="position: absolute;top: 460px">
      <div class="w3-container w3-cell w3-white" style="width: 75%;">
        {% if not measure %}
        <h5 style="text-align: center;" id = "mselect">Measurement : </h5>
        {% endif %}
        {% for m in measure %}
        <h5 style="text-align: center;" id = "mselect">Measurement : {{m.measure}}</h5>
        {% endfor %}
      </div>
    </div>


  <div class="w3-cell-row" style="position: absolute;top: 570px">
    <div class="w3-container w3-cell" style="width: 50%;">
      <button id = "submit" class="w3-container w3-ripple w3-btn w3-red" style="width: 100%; height: 30px;" >Submit</button>
    </div>
  </div>
</div>

<!-- Page Content -->
<div class="w3-overlay w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" id="myOverlay"></div>

<div class="w3-bar w3-black">
  <button class="w3-button w3-black w3-left " onclick="w3_open()">&#9776;</button>
  <a href="{% url 'bi:show' %}" class="w3-bar-item w3-button w3-hover-red" style="text-decoration:none;">Home</a>
  <a href="{% url 'bi:graph' %}" class="w3-bar-item w3-button w3-hover-blue" style="text-decoration:none;">Graph</a>
</div>

<div class="container" style="overflow:scroll;height:100%;width:80%;overflow:auto">
<table align="center" id="pivot" class="dataframe table table-bordered w3-grey" style="border:5px solid black; margin-top: 30px;"></table>


</div>


 
<script>
function w3_open() {
  document.getElementById("mySidebar").style.width = "50%";
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}
function deleteCol(o, id) {
   var id = id;
    $.get("{% url 'bi:delete_col' %}", {'data': id},function(data){
    });
    $(o).closest("tr").remove();
}
function deleteRow(o, id) {
   var id = id;
    $.get("{% url 'bi:delete_row' %}", {'data': id},function(data){
    });
    $(o).closest("tr").remove();
}
</script>
<script type="text/javascript"
    src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script>
    $(document).ready(
            function() {
                var linktext
                var measuretext = " ";
                $.ajaxSetup ({
                    // Disable caching of AJAX responses
                    cache: false
                });
                $('#pivot').load('/static/css/table.html');
                //$('.dataframe').load('/static/css/table.html');
                $('.bbb').click(function(){
                    measuretext=$(this).text();
                    $('#mselect').text('Measurement : '+ measuretext);
                });
                $('.aaa').click(function(){
                    linktext=$(this).text();
                    $('#select').text('Dimension : '+ linktext);
                });
                $('#colbut').click(function(){
                    $('#colTable').append('<tr><td class="tbl">'+linktext+'</td><td><button class="button" style="background-color:green; color:white;" type="submit"><b>+</b></button><button class="button" onclick="deleteCol(this)" style="background-color:red; color:white;"type="submit"><b>-</b></button></td></tr>')
                    $('#select').text('Select : ');
                    
                });
                $('#rowbut').click(function(){
                    $('#rowTable').append('<tr><td class="tbl">'+linktext+'</td><td><button class="button" style="background-color:green; color:white;" type="submit"><b>+</b></button><button class="button" onclick="deleteRow(this)" style="background-color:red; color:white;"type="submit"><b>-</b></button></td></tr>')
                    $('#select').text('Select : ');
                    
                });
                $('#submit').click(function(){
                    arrayc = []
                    arrayr = []
                    $('#colTable > tbody  > tr > td.tbl').each(function() {
                        value = $(this).text();
                        arrayc.push(value);
                    });
                    $('#rowTable > tbody  > tr > td.tbl').each(function() {
                        value = $(this).text();
                        arrayr.push(value);
                    });
                    $.get("{% url 'bi:col_select' %}", {'data': arrayc},function(data){
                    });
                    $.get("{% url 'bi:row_select' %}", {'data': arrayr},function(data){
                    });
                    $.get("{% url 'bi:measure_select' %}", {'data': measuretext},function(data){
                    });
                    location.href="{% url 'bi:pivot_page' %}";
                });
            });
</script>

</body>
</html>